[project]
name = "mazegen"
version = "0.1.0"
authors = [
    { name="abounoua", email="abounoua@students.42lyon.fr"},
    { name="arebilla", email="arebilla@students.42lyon.fr"},
]
description = "Maze generator"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.2",
    "pydantic>=2.12.5",
]

[project.scripts]
a-maze-ing = "a_maze_ing.main:main"

[dependency-groups]
a-maze-ing = [
    "mlx>=2.2",
]

dev = [
    "flake8>=7.3.0",
    "mypy>=1.19.1",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff>=0.15.2",
]

[tool.uv]
default-groups = "all"

[tool.uv.sources]
mlx = { path = "mlx/mlx-2.2-py3-none-any.whl" }

[tool.mypy]
strict = true

[tool.ruff]
line-length = 79

[tool.ruff.lint]
# see all options: https://docs.astral.sh/ruff/rules/
select = [
    # isort
    "I",
    # pyflakes
    "F",
    # error
    "E",
    # docstrings
    #"D101", "D102", "D103"
]
ignore = ["E731"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 79

[build-system]
requires = ["uv_build >= 0.10.7, <0.11.0"]
build-backend = "uv_build"
